FROM dockai:base

ENV TORCH_HOME=/workdir/data/.torch

# Install PyTorch
RUN pip3 install --no-cache-dir \
    torch==1.6.0 \
    torchvision==0.7.0

# Install PyTorch based packages
RUN pip3 install --no-cache-dir \
    pytorch-argus==0.1.2 \
    timm==0.2.1
