name: Build and push Docker images
on: [push]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Nvidia default runtime
        run: |
          sudo add-apt-repository ppa:graphics-drivers
          curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | \
            sudo apt-key add -
          distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
          curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
          sudo apt-get update
          sudo apt-get install nvidia-driver-440
          sudo apt-get install nvidia-container-runtime
          sudo cp docker_daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build Docker images
        run: |
          docker build -f ./docker/Dockerfile.base -t dockai:base .
          docker build -f ./docker/Dockerfile.pytorch -t dockai:pytorch .
          docker build -f ./docker/Dockerfile.tensor-stream -t dockai:tensor-stream .
