name: Build and push Docker images
on: [push]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker images
        run: |
          docker build -f ./docker/Dockerfile.base -t dockai:base .
          docker build -f ./docker/Dockerfile.pytorch -t dockai:pytorch .
