name: Build and push Docker images

on:
  push:
    paths-ignore:
    - 'README.md'
    - 'example/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          docker build -f ./docker/Dockerfile.base -t dockai:base .
          docker build -f ./docker/Dockerfile.pytorch -t dockai:pytorch .
          docker build -f ./docker/Dockerfile.tensor-stream -t dockai:tensor-stream .
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Push Docker images
        run: |
          registry="ghcr.io/osai-ai/dockai:$(date +%y).$(date +%m)"
          docker tag dockai:base $registry-base
          docker push $registry-base
          docker tag dockai:pytorch $registry-pytorch
          docker push $registry-pytorch
          docker tag dockai:tensor-stream  $registry-tensor-stream
          docker push $registry-tensor-stream
