name: Build and push Docker images
on: [push]
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Nvidia default runtime
        run: |
          sudo apt-get install nvidia-container-runtime
          sudo cp docker_daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build Docker images
        run: |
          docker build -f ./docker/Dockerfile.base -t dockai:base .
          docker build -f ./docker/Dockerfile.pytorch -t dockai:pytorch .
          docker build -f ./docker/Dockerfile.tensor-stream -t dockai:tensor-stream .
